### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by DavidSint** [mxp100/insomnia-plugin-openapi-export#1]
Hi Yuriy,

I was looking at your plugin, but with my very limited experience with Insomnia Plugins, I couldn't actually work out how to use it to export an API 😅

So, once this plugin is installed, how do you use it to an export an OpenAPI spec?

**Comment by mxp100** [comment]
ok, i add to readme short instructions in this week.
Using very simple -> choose you collection and in submenu (where built in export/import collection) "Export as OpenAPI 3.0", after several seconds select you base URL environment (using in you collection) or skip (if not needed). Required 1 base URL using for OpenAPI servers section.
P.S. Sorry for my english ;)

**Comment by DavidSint** [comment]
No problem, when I try to follow the instructions, I only see three export options: Insomnia v4 (JSON), Insomnia v4 (YAML), and HAR - HTTP Archive Format :( 

Not sure what I'm doing wrong as I have the plugin enabled in settings and I have refreshed the app.

**Comment by mxp100** [comment]
Export in collection option popup. Insomnia plugin system can't support add new export plugins to built-in exports.
![image](https://github.com/mxp100/insomnia-plugin-openapi-export/assets/8124083/450708b6-f31b-4ff4-8a77-abb301690f9d)

**Comment by jovial-snyder** [comment]
hey @mxp100 great plugin, thank you. I was also confused how to use it until i saw your screenshot. I would recommend updating the README with a section that explains how to use this plugin.
